/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gs.panel;

import gs.dialog.jdialogObat;
import gs.dialog.jdialogSupplier;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Fuji Nur Firdaus
 */
public class panelOrderObat extends javax.swing.JPanel {

    public final Connection conn = new koneksi().configDB(); //memanggil koneksi
    private DefaultTableModel tabmode;
    private int stokeObat = 0;
//    private String username;

    /**
     * Creates new form panelOrderObat
     */
    public panelOrderObat() {
//        this.username = username;
        initComponents();
        cetak.setVisible(false);
        btnBatal.setVisible(false);
        detailTableparent.setVisible(false);
        dataTableorder();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        panelTampil = new javax.swing.JPanel();
        scrollPaneWin111 = new gs.scroll.win11.ScrollPaneWin11();
        dataPemesanan = new gs.component.Table();
        btnTambah = new rojerusan.RSMaterialButtonRectangle();
        cetak = new rojerusan.RSMaterialButtonRectangle();
        btnBatal = new rojerusan.RSMaterialButtonRectangle();
        btnCari = new javax.swing.JTextField();
        fsdfd = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        detailTableparent = new javax.swing.JScrollPane();
        detailTable = new gs.component.Table();
        fsdfd1 = new javax.swing.JLabel();
        panelTambah = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        btnBatal1 = new rojerusan.RSMaterialButtonRectangle();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableSementara = new gs.component.Table();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idOrder = new javax.swing.JTextField();
        tanggal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kodeSup = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        namaSup = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        alamat = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        kodeOb = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        namaOb = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jml = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        satuan = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tambahSementara = new rojerusan.RSMaterialButtonRectangle();
        tambahSementara1 = new rojerusan.RSMaterialButtonRectangle();
        saveedit = new rojerusan.RSMaterialButtonRectangle();
        btnHapusOrder = new rojerusan.RSMaterialButtonRectangle();

        mainPanel.setLayout(new java.awt.CardLayout());

        panelTampil.setBackground(new java.awt.Color(255, 255, 255));

        scrollPaneWin111.setBorder(null);
        scrollPaneWin111.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        dataPemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dataPemesanan.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        dataPemesanan.setSelectionBackground(new java.awt.Color(45, 149, 150));
        dataPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataPemesananMouseClicked(evt);
            }
        });
        scrollPaneWin111.setViewportView(dataPemesanan);

        btnTambah.setBackground(new java.awt.Color(38, 80, 115));
        btnTambah.setText("ORDER");
        btnTambah.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        cetak.setBackground(new java.awt.Color(0, 153, 102));
        cetak.setText("CETAK");
        cetak.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(255, 204, 0));
        btnBatal.setText("BATAL");
        btnBatal.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnCari.setFont(new java.awt.Font("Poppins", 2, 14)); // NOI18N
        btnCari.setForeground(new java.awt.Color(153, 153, 153));
        btnCari.setText("Cari Disini ...");
        btnCari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        btnCari.setOpaque(false);
        btnCari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnCariFocusGained(evt);
            }
        });
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        btnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnCariKeyTyped(evt);
            }
        });

        fsdfd.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        fsdfd.setForeground(new java.awt.Color(0, 102, 102));
        fsdfd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fsdfd.setText("Form Riwayat Order");
        fsdfd.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        fsdfd.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 102, 102)));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gs/image/Search Folder.png"))); // NOI18N

        detailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        detailTableparent.setViewportView(detailTable);

        fsdfd1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        fsdfd1.setForeground(new java.awt.Color(0, 102, 102));
        fsdfd1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fsdfd1.setText("Detail Obat yang di Order");
        fsdfd1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        fsdfd1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 102, 102)));

        javax.swing.GroupLayout panelTampilLayout = new javax.swing.GroupLayout(panelTampil);
        panelTampil.setLayout(panelTampilLayout);
        panelTampilLayout.setHorizontalGroup(
            panelTampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTampilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fsdfd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTampilLayout.createSequentialGroup()
                        .addGroup(panelTampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(detailTableparent, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 1403, Short.MAX_VALUE)
                            .addGroup(panelTampilLayout.createSequentialGroup()
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 859, Short.MAX_VALUE)
                                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)))
                        .addGap(6, 6, 6))
                    .addComponent(fsdfd1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelTampilLayout.setVerticalGroup(
            panelTampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTampilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fsdfd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelTampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fsdfd1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(detailTableparent, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        mainPanel.add(panelTampil, "card2");

        panelTambah.setBackground(new java.awt.Color(255, 255, 255));

        judul.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        judul.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        judul.setText("Form Tambah Orderan Obat ke Supplier");
        judul.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        judul.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 102, 102)));

        btnBatal1.setBackground(new java.awt.Color(255, 204, 0));
        btnBatal1.setText("KEMBALI");
        btnBatal1.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnBatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatal1ActionPerformed(evt);
            }
        });

        tableSementara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableSementara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSementaraMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableSementara);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Id Order");

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tanggal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(idOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));

        jLabel8.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Data Supplier");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel6.setText("Kode Supplier");

        kodeSup.setBackground(new java.awt.Color(204, 204, 204));
        kodeSup.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel7.setText("Nama Supplier");

        namaSup.setBackground(new java.awt.Color(204, 204, 204));
        namaSup.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N

        jButton1.setText("pilih");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        alamat.setBackground(new java.awt.Color(204, 204, 204));
        alamat.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel15.setText("Alamat Supplier");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(alamat)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(kodeSup, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaSup, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodeSup)
                    .addComponent(namaSup)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(alamat)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));

        jLabel9.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Data Obat");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel11.setText("Kode Obat");

        kodeOb.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel12.setText("Nama Obat");

        namaOb.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N

        jButton2.setText("pilih");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jml.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlActionPerformed(evt);
            }
        });
        jml.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jmlKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jmlKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel13.setText("Jumlah");

        satuan.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel14.setText("Satuan");

        tambahSementara.setBackground(new java.awt.Color(0, 102, 102));
        tambahSementara.setText("TAMBAH OBAT");
        tambahSementara.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        tambahSementara.setPreferredSize(null);
        tambahSementara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahSementaraActionPerformed(evt);
            }
        });

        tambahSementara1.setBackground(new java.awt.Color(0, 153, 51));
        tambahSementara1.setText("SELESAI");
        tambahSementara1.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        tambahSementara1.setPreferredSize(null);
        tambahSementara1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahSementara1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(namaOb, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                    .addComponent(kodeOb, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(tambahSementara, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tambahSementara1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jml, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(satuan, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodeOb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(1, 1, 1)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(namaOb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(satuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahSementara, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahSementara1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tambahSementara, tambahSementara1});

        saveedit.setBackground(new java.awt.Color(0, 102, 102));
        saveedit.setText("EDIT ORDER");
        saveedit.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        saveedit.setPreferredSize(null);
        saveedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveeditActionPerformed(evt);
            }
        });

        btnHapusOrder.setBackground(new java.awt.Color(204, 0, 0));
        btnHapusOrder.setText("Hapus");
        btnHapusOrder.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        btnHapusOrder.setPreferredSize(null);
        btnHapusOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTambahLayout = new javax.swing.GroupLayout(panelTambah);
        panelTambah.setLayout(panelTambahLayout);
        panelTambahLayout.setHorizontalGroup(
            panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTambahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelTambahLayout.createSequentialGroup()
                        .addGroup(panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTambahLayout.createSequentialGroup()
                                .addComponent(saveedit, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnHapusOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE))
                            .addComponent(jScrollPane2)))
                    .addGroup(panelTambahLayout.createSequentialGroup()
                        .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );
        panelTambahLayout.setVerticalGroup(
            panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTambahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBatal1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTambahLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addGroup(panelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveedit, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(btnHapusOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(panelTambahLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        panelTambahLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnHapusOrder, saveedit});

        mainPanel.add(panelTambah, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void dataPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataPemesananMouseClicked

//            orderDetailtampil();
        btnBatal.setVisible(true);
        cetak.setVisible(true);
        detailTableparent.setVisible(true);
        btnTambah.setVisible(false);

        int bar = dataPemesanan.getSelectedRow();
        if (bar == -1) {
            JOptionPane.showMessageDialog(null, "Silakan pilih baris terlebih dahulu.");
            return; // Keluar dari method jika tidak ada baris yang dipilih
        }

        // Ambil id_pemesanan dari baris yang dipilih
        String c = tabmode.getValueAt(bar, 2).toString(); // Pastikan ini sesuai dengan kolom yang benar

        // Tampilkan detail pemesanan
        orderDetailtampil(c); // Kirim ID pemesanan ke metode

    }//GEN-LAST:event_dataPemesananMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        jml.requestFocus();

        SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd"); // Atur format tanggal yang diinginkan
        String tanggalNow = fm.format(new Date());
        tanggal.setText(tanggalNow);
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(panelTambah);
        mainPanel.repaint();
        mainPanel.revalidate();
//        btnTambah1.setVisible(false);
        btnHapusOrder.setVisible(false);
        saveedit.setVisible(false);
        idOrder.setEditable(false);
        tanggal.setEditable(false);
        idAuto();
        deletesementara();
      datatablesementara();
//        btnTambah1.setText("SIMPAN");
//
//        if (btnTambah.getText().equals("UBAH")){
//            judul.setText("Form Ubah Data Obat");
//            ubahDataTabel();
//        } else if (btnTambah.getText().equals("TAMBAH")){
////            judul.setText("Form Orde");
//                        idAuto();
//        }

    }//GEN-LAST:event_btnTambahActionPerformed

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        hapusData();
    }//GEN-LAST:event_cetakActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        btnTambah.setVisible(true);
        cetak.setVisible(false);
        btnBatal.setVisible(false);
        btnTambah.setBackground(new Color(38, 80, 115));
        detailTableparent.setVisible(false); // Ini akan menyembunyikan tabel beserta header
        panelTampil.repaint();
        panelTampil.revalidate();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnCariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCariFocusGained
        btnCari.setText("");
    }//GEN-LAST:event_btnCariFocusGained

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnCariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCariKeyTyped
        String sqlPencarian = "select * from tb_pemesanan where kode_obat like '%" + btnCari.getText() + "%' or nama_obat like '%" + btnCari.getText() + "%' or id_pemesaanan like '%" + btnCari.getText() + "%'or tanggal like '%" + btnCari.getText() + "%'";
        pencarian(sqlPencarian);
//        lebarKolom();
    }//GEN-LAST:event_btnCariKeyTyped

    private void btnBatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatal1ActionPerformed
        mainPanel.removeAll();
        mainPanel.add(panelTampil);
        mainPanel.repaint();
        mainPanel.revalidate();
        resetForm();
        btnBatal.setVisible(false);
        dataTableorder();
        deletesementara();
//        lebarKolom();
    }//GEN-LAST:event_btnBatal1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jdialogSupplier dialog = new jdialogSupplier(null, true);
        dialog.setVisible(true);

        kodeSup.setText(dialog.ms.getKode_supplier());
        namaSup.setText(dialog.ms.getNama_supplier());
        alamat.setText(dialog.ms.getAlamat());
        kodeSup.setEditable(false);
        namaSup.setEditable(false);
        alamat.setEditable(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jdialogObat dialog = new jdialogObat(null, true);
        dialog.setVisible(true);

        kodeOb.setText(dialog.mo.getKode_obat());
        namaOb.setText(dialog.mo.getNama_obat());
        satuan.setText(dialog.mo.getSatuan());
        kodeOb.setEditable(false);
        namaOb.setEditable(false);
        satuan.setEditable(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void saveeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveeditActionPerformed
        updateOrder();
        namaOb.setText("");
        jml.setText("");
        satuan.setText("");
        kodeOb.setText("");

        saveedit.setVisible(false);
        btnHapusOrder.setVisible(false);
        tableSementara.clearSelection();
        tambahSementara.setText("TAMBAH OBAT");
        tambahSementara.setBackground(new Color(0, 102, 102));
        tambahSementara1.setVisible(true);
    }//GEN-LAST:event_saveeditActionPerformed

    private void btnHapusOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusOrderActionPerformed
        hapusPesanSementara();
        saveedit.setVisible(false);
        btnHapusOrder.setVisible(false);
        tableSementara.clearSelection();
        tambahSementara.setText("TAMBAH OBAT");
        tambahSementara.setBackground(new Color(0, 102, 102));
        tambahSementara1.setVisible(true);
    }//GEN-LAST:event_btnHapusOrderActionPerformed

    private void tambahSementaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahSementaraActionPerformed
        if (tambahSementara.getText().equals("TAMBAH OBAT")) {
            String sql = "insert into tb_sementara_pesan values (?,?,?,?)";

            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, kodeOb.getText());
                stat.setString(2, namaOb.getText());
                stat.setString(3, jml.getText());
                stat.setString(4, satuan.getText());
                stat.executeUpdate();
//            JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
                //            String refresh = "select * from tb_barang";
                resetForm();
                dataTableorder();
                idAuto();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan" + e);
            }

            datatablesementara();
        } else if (tambahSementara.getText().equals("BATAL")) {
            namaOb.setText("");
            jml.setText("");
            satuan.setText("");
            kodeOb.setText("");

            saveedit.setVisible(false);
            btnHapusOrder.setVisible(false);
            tableSementara.clearSelection();
            tambahSementara.setText("TAMBAH OBAT");
            tambahSementara.setBackground(new Color(0, 102, 102));
            tambahSementara1.setVisible(true);
        }
    }//GEN-LAST:event_tambahSementaraActionPerformed

    private void tableSementaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSementaraMouseClicked
        tambahSementara.setText("BATAL");
        tambahSementara.setBackground(Color.ORANGE);
        saveedit.setVisible(true);
        btnHapusOrder.setVisible(true);
        tambahSementara1.setVisible(false);

        int bar = tableSementara.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();

        kodeOb.setText(b);
        namaOb.setText(c);
        jml.setText(d);
        satuan.setText(e);

    }//GEN-LAST:event_tableSementaraMouseClicked

    private void tambahSementara1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahSementara1ActionPerformed
        simpanPesanan();
    }//GEN-LAST:event_tambahSementara1ActionPerformed

    private void jmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlActionPerformed

    }//GEN-LAST:event_jmlActionPerformed

    private void jmlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmlKeyTyped
//      try {
//        // Ambil jumlah barang yang diinputkan pengguna
//        int jumlah = Integer.parseInt(jml.getText() + evt.getKeyChar());
//        
//        // Jika jumlah melebihi stok yang tersedia, tampilkan pesan peringatan
//        if (jumlah > stokeObat) {
//            evt.consume(); // Hentikan input jika melebihi stok
//            JOptionPane.showMessageDialog(this, 
//                "Stok tidak cukup! Stok yang tersedia: " + stokeObat, 
//                "Peringatan", 
//                JOptionPane.WARNING_MESSAGE);
//        }
//    } catch (NumberFormatException e) {
//        // Jika input bukan angka, abaikan
//        evt.consume();
//    }
    }//GEN-LAST:event_jmlKeyTyped

    private void jmlKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmlKeyReleased
//        String kodeObat = kodeOb.getText();
//    if (!kodeObat.isEmpty()) {
//   jumlahStok(kodeObat);
//    }
    }//GEN-LAST:event_jmlKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private rojerusan.RSMaterialButtonRectangle btnBatal;
    private rojerusan.RSMaterialButtonRectangle btnBatal1;
    private javax.swing.JTextField btnCari;
    private rojerusan.RSMaterialButtonRectangle btnHapusOrder;
    private rojerusan.RSMaterialButtonRectangle btnTambah;
    private rojerusan.RSMaterialButtonRectangle cetak;
    private gs.component.Table dataPemesanan;
    private gs.component.Table detailTable;
    private javax.swing.JScrollPane detailTableparent;
    private javax.swing.JLabel fsdfd;
    private javax.swing.JLabel fsdfd1;
    private javax.swing.JTextField idOrder;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jml;
    private javax.swing.JLabel judul;
    private javax.swing.JTextField kodeOb;
    private javax.swing.JTextField kodeSup;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField namaOb;
    private javax.swing.JTextField namaSup;
    private javax.swing.JPanel panelTambah;
    private javax.swing.JPanel panelTampil;
    private javax.swing.JTextField satuan;
    private rojerusan.RSMaterialButtonRectangle saveedit;
    private gs.scroll.win11.ScrollPaneWin11 scrollPaneWin111;
    private gs.component.Table tableSementara;
    private rojerusan.RSMaterialButtonRectangle tambahSementara;
    private rojerusan.RSMaterialButtonRectangle tambahSementara1;
    private javax.swing.JTextField tanggal;
    // End of variables declaration//GEN-END:variables

    private void ubahDataTabel() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void hapusData() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void pencarian(String sqlPencarian) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void dataTable() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void resetForm() {
        namaOb.setText("");
        jml.setText("");
        satuan.setText("");
        kodeOb.setText("");

        idAuto();
    }

    private void perbaruiData() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void simpanData() {
        String sql = "insert into tb_pemesanan values (?,?,?)";

        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, idOrder.getText());
            stat.setString(2, tanggal.getText());
            stat.setString(3, kodeSup.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            //            String refresh = "select * from tb_barang";
            resetForm();
            dataTableorder();
            idAuto();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan" + e);
        }

        String sql2 = "insert into tb_detail_pemesanan values (?,?,?,?)";

        try {
            PreparedStatement stat = conn.prepareStatement(sql2);
            stat.setString(1, idOrder.getText());
            stat.setString(2, kodeOb.getText());
            stat.setString(3, namaOb.getText());
            stat.setString(4, jml.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            //            String refresh = "select * from tb_barang";
            resetForm();
            dataTableorder();
            idAuto();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan" + e);
        }
    }

    private void dataTableorder() {
        Object[] Baris = {"No", "Tanggal", "Id Pemesanan", "Kode Supplier", "Nama Supplier"};
        tabmode = new DefaultTableModel(null, Baris);
        dataPemesanan.setModel(tabmode);
        String sql = "select * from tb_pemesanan order by tanggal asc";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String a = hasil.getString("tanggal");
                String b = hasil.getString("id_pemesanan");
                String c = hasil.getString("kode_supplier");
                String d = hasil.getString("nama_supplier");
                String[] data = {"", a, b, c, d};
                tabmode.addRow(data);
                noTable();
//                lebarKolom();
            }
        } catch (Exception e) {
        }
    }

    private void idAuto() {
        PreparedStatement st = null;
        ResultSet rs = null;
        String urutan = null;

        Date now = new Date();
        SimpleDateFormat tanggal = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat noformat = new SimpleDateFormat("yyMM");
        String tgl = tanggal.format(now);
        String no = noformat.format(now);

        String sql = "SELECT RIGHT (id_pemesanan,3) AS Nomor FROM tb_pemesanan WHERE id_pemesanan LIKE 'ORD" + no + "%' ORDER BY id_pemesanan DESC LIMIT 1";

        try {
            st = conn.prepareStatement(sql);
            rs = st.executeQuery();

            if (rs.next()) {
                int nomor = Integer.parseInt(rs.getString("Nomor"));
                nomor++;
                urutan = "ORD" + no + String.format("%03d", nomor);
                idOrder.setText(urutan);
            } else {
                urutan = "ORD" + no + "001";
                idOrder.setText(urutan);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void noTable() {
        int Baris = tabmode.getRowCount();
        for (int a = 0; a < Baris; a++) {
            String nomor = String.valueOf(a + 1);
            tabmode.setValueAt(nomor + ".", a, 0);
        }
    }

    private void datatablesementara() {
        Object[] Baris = {"No", "Kode Obat", "Nama Obat", "Jumlah", "Satuan"};
        tabmode = new DefaultTableModel(null, Baris);
        tableSementara.setModel(tabmode);
        String sql = "select * from tb_sementara_pesan";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String a = hasil.getString("kode_obat");
                String b = hasil.getString("nama_obat");
                String c = hasil.getString("jumlah");
                String d = hasil.getString("satuan");
                String[] data = {"", a, b, c, d};
                tabmode.addRow(data);
                noTable();
//                lebarKolom();
            }
        } catch (Exception e) {
        }
    }

//    private void ambilStokObat(String kodeObat) {
//        String query = "SELECT jumlah FROM tb_obat WHERE kode_obat = ?";
//    try (PreparedStatement ps = conn.prepareStatement(query)) {
//        ps.setString(1, kodeObat);
//        ResultSet rs = ps.executeQuery();
//        
//        if (rs.next()) {
//            stokObat = rs.getInt("stok");  // Simpan stok ke variabel stokBarang
//        } else {
//            stokObat = 0;  // Jika barang tidak ditemukan, set stok ke 0
//        }
//    } catch (SQLException e) {
//        e.printStackTrace();
//    }
//    }
//    private void jumlahStok(String kodeObat) {
//       String query = "SELECT jumlah FROM tb_obat WHERE kode_obat = ?";
//    try (PreparedStatement ps = conn.prepareStatement(query)) {
//        ps.setString(1, kodeObat);
//        ResultSet rs = ps.executeQuery();
//        
//        if (rs.next()) {
//            stokeObat = rs.getInt("jumlah");  // Simpan stok ke variabel stokBarang
//        } else {
//            stokeObat = 0;  // Jika barang tidak ditemukan, set stok ke 0
//        }
//    } catch (SQLException e) {
//        e.printStackTrace();
//    }
//    }
    private void updateOrder() {
        String sql = "UPDATE tb_sementara_pesan SET kode_obat=?,nama_obat=?,jumlah=?,satuan=? WHERE kode_obat='" + kodeOb.getText() + "'";

        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, kodeOb.getText());
            stat.setString(2, namaOb.getText());
            stat.setString(3, jml.getText());
            stat.setString(4, satuan.getText());
            stat.executeUpdate();
//            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");

            //            String refresh = "select * from tb_barang";
            resetForm();
            datatablesementara();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah " + e);
        }
    }

    private void hapusPesanSementara() {
        int bar = tableSementara.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();

        int ok = JOptionPane.showConfirmDialog(null, " Apakah Anda Yakin Ingin "
                + "Menghapus Data", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            String sql = "delete from tb_sementara_pesan where kode_obat='" + b + "'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
//                JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus");

                datatablesementara();
                resetForm();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus" + ex);
            }
        }
    }

    private void simpanPesanan() {
        // Misalkan ini adalah metode yang dipanggil ketika tombol "Simpan Pemesanan" diklik
        
        try {
            // Mulai transaksi
            conn.setAutoCommit(false);

            // 1. Insert ke tabel pemesanan
            String sqlPemesanan = "INSERT INTO tb_pemesanan (id_pemesanan, tanggal, kode_supplier,nama_supplier) VALUES (?, ?, ?,?)";
            PreparedStatement statPemesanan = conn.prepareStatement(sqlPemesanan);
            statPemesanan.setString(1, idOrder.getText());  // id_pemesanan dari form
            statPemesanan.setDate(2, java.sql.Date.valueOf(tanggal.getText())); // tanggal dari form
            statPemesanan.setString(3, kodeSup.getText());  // kode_supplier dari form
            statPemesanan.setString(4, namaSup.getText());  // kode_supplier dari form
//            statPemesanan.setString(5, getUsername());  // kode_supplier dari form
            statPemesanan.executeUpdate();

            // 2. Insert ke tabel detail_pemesanan dari tb_sementara_pesan
            String sqlDetail = "INSERT INTO tb_detail_pemesanan (id_pemesanan, kode_obat, nama_obat, jumlah) "
                    + "SELECT ?, kode_obat, nama_obat, jumlah FROM tb_sementara_pesan";
            PreparedStatement statDetail = conn.prepareStatement(sqlDetail);
            statDetail.setString(1, idOrder.getText());  // id_pemesanan yang sama dengan pemesanan
            statDetail.executeUpdate();

            // 3. Commit transaksi
            conn.commit();
            JOptionPane.showMessageDialog(null, "Data Pemesanan Berhasil Ditambahkan");

            // 4. Clear tb_sementara_pesan setelah data dipindahkan
            String sqlClear = "DELETE FROM tb_sementara_pesan";
            PreparedStatement statClear = conn.prepareStatement(sqlClear);
            statClear.executeUpdate();
            updateOrder();
            kodeSup.setText("");
            namaSup.setText("");
            alamat.setText("");

        } catch (SQLException e) {
            // Rollback jika ada error
            try {
                conn.rollback();
                JOptionPane.showMessageDialog(null, "Data Pemesanan Gagal Ditambahkan: " + e.getMessage());
            } catch (SQLException rollbackEx) {
                rollbackEx.printStackTrace();
            }
        } finally {
            // Kembalikan koneksi ke mode Auto-Commit
            try {
                conn.setAutoCommit(true);
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }

    private void orderDetailtampil(String idPemesanan) {
       DefaultTableModel model = (DefaultTableModel) detailTable.getModel();
    model.setRowCount(0); // Menghapus semua baris dari tabel detail

    // Mengatur header untuk tabel detail
    Object[] Baris = {"No", "Id Pemesanan", "Kode Obat", "Nama Obat", "Jumlah"};
    model.setColumnIdentifiers(Baris); // Set header kolom

    // Menggunakan PreparedStatement untuk mencegah SQL Injection
    String sql = "SELECT * FROM tb_detail_pemesanan WHERE id_pemesanan = ?";
    try {
        PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, idPemesanan);
        ResultSet hasil = pstmt.executeQuery();

        // Mengisi tabel detail
        int no = 1; // Nomor urut
        while (hasil.next()) {
            String e = hasil.getString("id_pemesanan");
            String f = hasil.getString("kode_obat");
            String g = hasil.getString("nama_obat");
            String h = hasil.getString("jumlah");
            String[] data = {String.valueOf(no++), e, f, g, h}; // Menambahkan data ke tabel
            model.addRow(data);
        }

        detailTable.setVisible(true); // Tampilkan detailTable setelah diisi
    } catch (SQLException e) {
        e.printStackTrace(); // Menangani exception dengan mencetak stack trace
    }
    }

//    private String getUsername() {
//        return username;
//    }

    private void deletesementara(){
        String sqlClear = "DELETE FROM tb_sementara_pesan";
            try {
                PreparedStatement stat=conn.prepareStatement(sqlClear);
                stat.executeUpdate();
                dataTableorder();
            } catch (SQLException ex) {
                
            }
            kodeSup.setText("");
            namaSup.setText("");
            alamat.setText("");
    }

}
